name: safqa
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  dio: ^4.0.6
  sizer: ^2.0.15
  getwidget: ^3.0.1
  page_view_indicators: ^2.0.0
  email_validator: ^2.1.17
  intl_phone_field: ^3.1.0
  pin_code_fields: ^7.4.0
  # shared_preferences: ^0.5.12
  shared_preferences: ^2.0.15
  flutter_zoom_drawer: ^3.0.3
  fl_chart: ^0.55.2
  textfield_datepicker: ^0.1.0
  intl: ^0.17.0
  path_provider: ^2.0.11
  dotted_border: ^2.0.0+2
  file_picker: ^5.2.4
  badges: ^2.0.3
  http_parser: ^4.0.2
  syncfusion_flutter_sliders: ^20.3.50
  expandable: ^5.0.1
  flutter_switch: ^0.3.2
  eva_icons_flutter: ^3.1.0
  # awesome_select: ^6.0.0
  chips_choice: ^3.0.0
  multiselect: ^0.0.7
  lottie: ^2.0.0
  font_awesome_flutter: ^10.2.1
  flutter_svg: ^1.1.6
  shimmer: ^2.0.0
  searchfield: ^0.7.2
  # path_provider: ^1.6.28
  flutter_form_builder: ^7.7.0
  flutter_secure_storage: ^4.2.1
  restart_app: ^1.1.0
  printing: ^5.9.3
  csv: ^5.0.1
  excel: ^2.0.1
  permission_handler: ^10.2.0
  url_launcher: ^6.1.9
  easy_image_viewer: ^1.2.0
  font_awesome_flutter_named: ^1.1.1+4
  jwt_decode: ^0.3.1
  change_app_package_name: ^1.1.0
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.9

  # dartarabic: ^0.1.2
  # file_selector: ^0.9.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.11.0"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "C:/Users/Mohammed Al-Ammourie/Desktop/f-logo.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "C:/Users/Mohammed Al-Ammourie/Desktop/f-logo.png"
  adaptive_icon_padding: true
  min_sdk_android: 21 # android min sdk min:16, default 21

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo/0.75x/logo.png
    - assets/images/logo/logo.png
    - assets/images/logo/1.5x/logo.png
    - assets/images/logo/2.0x/logo.png
    - assets/images/logo/3.0x/logo.png
    - assets/images/logo/4.0x/logo.png
    - assets/images/language_page_wallpaper.png
    - assets/images/welcome_background.png
    - assets/images/intro1.png
    - assets/images/intro2.png
    - assets/images/intro3.png
    - assets/images/intro4.png
    - assets/images/intro5.png
    - assets/images/circle1.png
    - assets/images/circle2.png
    - assets/images/logo-white.png
    - assets/images/Kuwait.png
    - assets/images/uae.png
    - assets/images/home_business.png
    - assets/images/licomp.png
    - assets/images/finger-print.png
    - assets/images/done.png
    - assets/images/menu.png
    - assets/images/t.png
    - assets/images/t2.png
    - assets/images/inv_item.png
    - assets/images/tick.png
    - assets/images/double_forward_icon.png
    - assets/images/btn_wallpaper.png
    - assets/images/notification.png
    - assets/images/chart.png
    - assets/images/stamp.png
    - assets/images/create_invoice.png
    - assets/images/filter.png
    - assets/images/pending.png
    - assets/images/barcode.png
    - assets/images/warning.png
    - assets/images/id.png
    - assets/images/passport.png
    - assets/images/license.png
    - assets/images/trash.svg
    - assets/email.zip
    - assets/message.zip

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Medium.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
