import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          "english": "English",
          "send_invoice_by": "Send Invoice By",
          "customer_email": "Customer Email",
          "customer_refrence": "Customer Reference",
          "arabic": "Arabic",
          "disable": "Disable",
          "enable": "Enable",
          'login': 'Login',
          'signup': 'Sign Up',
          'start': 'let\'s Start',
          'skip': 'skip',
          'welcome': 'Welcome',
          'password': 'Password',
          'email': 'Email',
          'remember': 'Remember me',
          'forget_pass': 'Forgot your password?',
          'or_using_fast_login_by_fingerprint':
              'Or using fast login by fingerprint',
          'dont_have_an_account': 'Don\'t have an account?',
          'create_an_account': 'Create an account',
          'please_enter_a_valid_email': 'Please enter a valid email',
          'password_should_contain_more_than_5_characters':
              'Password should contain more than 5 characters',
          'generate': 'Generate',
          'collect': 'Collect',
          'keep': 'Keep',
          'sell': 'Sell',
          'ship': 'Ship',
          'generate_content': 'Invoices & Payment Links',
          'collect_content': 'Money on the go',
          'keep_content': 'Record of your business activites',
          'sell_content': 'Online with ease',
          'ship_content': 'Products with DHL & Aramex',
          "create_new_invoice": "Create a New Invoice",
          "invoices": "Invoices",
          "quick_invoices": "Quick Invoices",
          "payment_links": "Payment Links",
          "invoice_id": "Invoice Id",
          "invoice_date": "Invoice Date",
          "currency": "Currency",
          "is_open_invoice": "Is Open Invoice",
          "discount_available": "Discount Available",
          "expiry_date": "Expiry Date",
          "start_date": "Start Date",
          "end_date": "End Date",
          "time": "Time",
          "remind_after": "Remind After",
          "optional": "Optional",
          "recurring_interval": "Recurring Interval",
          "language_of_invoice": "Language of the invoice",
          "attach_file": "Attach File",
          "comments": "Comments",
          "terms_conditions": "Terms & Conditions",
          "customer_info": "Customer Info",
          "customer_name": "Customer Name",
          "customer_phone_number": "Customer Phone Number",
          "invoice_items": "Invoice Items",
          "discount_type": "Discount Type",
          "discount_value": "Discount Value",
          "create_invoice": "Create Invoice",
          "edit_invoice": "Edit Invoice",
          "edit": "Edit",
          "remove": "Remove",
          'total': "Total",
          'tax': "Tax",
          'days': "Days",
          "save": "Save",
          "add": "Add",
          "product_name": "Product Name",
          "unit_price": "Unit Price",
          "quantity": "Quantity",
          "invoice_value": "Invoice Value",
          "invoice_l_c_value": "Invoice Local Currency Value",
          "pl_id": "Payment Link Id",
          "pl_date": "Payment Link Date",
          "pl_url_title": "Payment Link Url Title",
          "pl_active": "Is the Payment Link Active?",
          "yes": "Yes",
          "no": "No",
          "f_p": "Fixed Price",
          "p_v": "Payment Value",
          "pl_lang": "Language of Payment Link",
          "create_link": "Create Link",
          "search": "Search ...",
          "fixed": "Fixed",
          "rate": "Rate",
          "changable": "Changable",
          "min_v": "Min Value",
          "max_v": "Max Value",
          "pl_dateils": "Payment Link Details",
          "pl_inf": "Payment Link Info",
          "date_created": "Date Created",
          "type": "Type",
          "pl_url": "Payment Url",
          "copy_link": "Copy Link",
          "vendor": "Vendor",
          "pl_amount": "Payment Amount",
          "pl_title": "Payment Link Title",
          "pl_ref": "Payment Link Refrence",
          "language": "Language",
          "active": "Active",
          "inactive": "InActive",
          "create_payment_link": "Create Payment Link",
          "edit_payment_link": "Edit Payment Link",
          "pl_open": "Open Payment Link?",
          "reset_password": "Reset Password",
          "change_password": "Change Password",
          "current_password": "Currenr Password",
          "new_password": "New Password",
          "confirm_password": "Confirm Password",
          "write_your_email": "Write Your Email",
          "write_your_ph_num": "Write Your Phone Number",
          "next": "Next",
          "try_ph_num": "Try with your Phone Number",
          "try_email": "Try with your Email",
          "check_your_phone_messages": "Check Your phone messages",
          "check_your_email": "Check Your Email",
          "phone_c":
              "Messages will be sent to your phone please check the message",
          "email_c":
              "Messages will be sent to your email please check the message",
        },
        'ar_SYR': {
          "edit": "تعديل",
          "remove": "حذف",
          'login': 'الدخول',
          'signup': 'التسجيل',
          'start': 'دعنا نبدأ',
          'skip': 'تخطي',
          'welcome': 'مرحباً بك',
          'password': 'كلمة السر',
          'email': 'البريد الإلكتروني',
          'remember': 'تذكر كلمة السر',
          'forget_pass': 'هل نسيت كلمة السر؟',
          'or_using_fast_login_by_fingerprint': 'أو سجل دخول باستخدام البصمة',
          'dont_have_an_account': 'ليس لديك حساب؟',
          'create_an_account': 'أنشئ حساباً',
          'please_enter_a_valid_email': 'أدخل بريداً إلكترونياً صالحاً',
          'password_should_contain_more_than_5_characters':
              'يجب أن تحتوي كلمة السر 5 محارف على الأقل',
          'generate': 'إنشاء',
          'collect': 'جمع',
          'keep': 'سجل',
          'sell': 'بع',
          'ship': 'اشحن',
          'generate_content': 'الفواتير وروابط الدفع',
          'collect_content': 'الأموال أثناء التنقل',
          'keep_content': 'أنشطة عملك',
          'sell_content': 'على الإنترنت بكل سهولة',
          'ship_content': ' المنتجات مع DHL و Aramex',
          "create_new_invoice": "إنشاء فاتورة جديدة",
          "create_quick_invoice": "إنشاء فاتورة بسرعة",
          "create_payment_link": "إنشاء رابط الدفع",
          "edit_payment_link": "تعديل رابط الدفع",
          "invoices": "الفواتير",
          "quick_invoices": "الفواتير السريعة",
          "payment_links": "روابط الدفع",
          "invoice_id": "معرف الفاتورة",
          "invoice_date": "تاريخ الفاتورة",
          "currency": "العملة",
          "is_open_invoice": "فاتورة مفتوحة؟",
          "discount_available": "هل يوجد تخفيض؟",
          "discount_type": "نوع التخفيض",
          "discount_value": "قيمة التخفيض",
          "expiry_date": "تاريخ الانتهاء",
          "time": "الوقت",
          "remind_after": "ذكرني بعد",
          "optional": "اختياري",
          "recurring_interval": "تتكرر كل ",
          "language_of_invoice": "لغة الفاتورة",
          "attach_file": "أرفق ملف",
          "comments": "التعليقات",
          "terms_conditions": "البنود و الظروف",
          "customer_info": "معلومات الزبون",
          "customer_name": "اسم الزبون",
          "customer_phone_number": "رقم هاتف الزبون",
          "customer_email": "إيميل الزبون",
          "send_invoice_by": "إرسال الفاتورة بواسطة",
          "invoice_items": "عناصر الفاتورة",
          "create_invoice": "أنشئ الفاتورة",
          "edit_invoice": "تعديل الفاتورة",
          'total': "المجمل",
          'tax': "ضريبة",
          'days': "أيام",
          "start_date": "تاريخ البدء",
          "end_date": "تاريخ الانتهاء",
          "english": "الإنجليزية",
          "arabic": "العربية",
          "disable": "تعطيل",
          "enable": "تفعيل",
          "customer_refrence": "مرجع الزبون",
          "save": "حفظ",
          "add": "إضافة",
          "product_name": "اسم المنتج",
          "unit_price": "سعر المنتج",
          "quantity": "الكمية",
          "invoice_value": "قيمة الفاتورة",
          "invoice_l_c_value": "قيمة الفاتورة بالعملة المحلية",
          "pl_id": "معرف رابط الدفع",
          "pl_date": "تاريخ رابط الدفع",
          "pl_url_title": "عنوان رابط الدفع",
          "pl_active": "هل رابط الدفع فعال؟",
          "yes": "نعم",
          "no": "لا",
          "f_p": "سعر ثابت",
          "p_v": "قيمة الدفع",
          "pl_lang": "لغة رابط الدفع",
          "create_link": "إنشاء الرابط",
          "search": "بحث ...",
          "fixed": "ثابت",
          "rate": "نسبة",
          "changable": "متغير",
          "min_v": "القيمة الصغرى",
          "max_v": "القيمة الكبرى",
          "pl_dateils": "تفاصيل رابط الدفع",
          "pl_inf": "معلومات رابط الدغع",
          "date_created": "تاريخ الإنشاء",
          "type": "النوع",
          "pl_url": "رابط الدفع",
          "copy_link": "نسخ الرابط",
          "vendor": "البائع",
          "pl_amount": "قيمة الدفع",
          "pl_title": "عنوان رابط الدفع",
          "pl_ref": "مرجع رابط الدفع",
          "language": "اللغة",
          "active": "فعال",
          "inactive": "غير فعال",
          "pl_open": "رابط دفع مفتوح؟",
          "reset_password": "إعادة تعيين كلمة المرور",
          "write_your_email": "اكتب بريدك الإلكتروني هنا",
          "write_your_ph_num": "اكتب رقم هاتفك هنا",
          "next": "التالي",
          "try_ph_num": "إعادة تعيين باستخدام رقم الهاتف",
          "try_email": "إعادة تعيين باستخدام البريد الالكتروني",
          "check_your_phone_messages": "تفقد الرسائل في هاتفك",
          "check_your_email": "تفقد بريدك الإلكتروني",
          "phone_c": "سيتم إرسال الرسائل إلى هاتفك ، يرجى التحقق من الرسالة",
          "email_c":
              "سيتم إرسال الرسائل إلى بريدك الإلكتروني ، يرجى التحقق من الرسالة",
          "change_password": "تغيير كلمة السر",
          "current_password": "كلمة السر الحالية",
          "new_password": "كلمة السر الجديدة",
          "confirm_password": "تأكيد كلمة السر",
        }
      };
}
